name: C Build CI (Makefile)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install clang
      run: sudo apt-get update && sudo apt-get install -y clang make
    - name: make
      run: make
